[workspace]
resolver = "2"

members = ["day-*", "all-days"]
default-members = ["day-*"]

[workspace.dependencies]
tracing = "0.1.40"
divan = "0.1.4"
rayon = "1.8"

[profile.flamegraph]
inherits = "dev"
debug = true

[profile.flamegraph-r]
inherits = "release"
debug = true
