[package]
name = "day_02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = { workspace = true }

[[bench]]
name = "day_02-bench"
path = "benches/benchmark.rs"
harness = false


